on:
    push:
        tags:
            - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Navigate to datapacks
          run: cd $GITHUB_WORKSPACE/datapacks/creeper-birthday-party/

        - name: Zip Data Pack
          uses: montudor/action-zip@v1
          with:
            args: zip -qq -r $GITHUB_WORKSPACE/creeper-birthday-party-datapack-${{ github.ref }}.zip . -i data/* pack.*

        - name: Navigate to resourcepacks
          run: cd $GITHUB_WORKSPACE/resourcepacks/creeper-birthday-party/

        - name: Zip Resource Pack
          uses: montudor/action-zip@v1
          with:
            args: zip -qq -r $GITHUB_WORKSPACE/creeper-birthday-party-resourcepack-${{ github.ref }}.zip . -i assets/* pack.* README.md

        - name: Create github Release
          id: create_release
          uses: actions/create-release@v1
          env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
              tag_name: ${{ github.ref }}
              release_name: ${{ github.ref }}
              draft: true
              prerelease: false

        - name: Upload datapack
          uses: actions/upload-release-asset@v1.0.1
          env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
              upload_url: ${{ steps.create_release.outputs.upload_url }}
              asset_path: $GITHUB_WORKSPACE/creeper-birthday-party-datapack-${{ github.ref }}.zip
              asset_name: creeper-birthday-party-datapack-${{ github.ref }}.zip
              asset_content_type: application/zip

        - name: Upload resourcepack
          uses: actions/upload-release-asset@v1.0.1
          env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
              upload_url: ${{ steps.create_release.outputs.upload_url }}
              asset_path: $GITHUB_WORKSPACE/creeper-birthday-party-resourcepack-${{ github.ref }}.zip
              asset_name: creeper-birthday-party-resourcepack-${{ github.ref }}.zip
              asset_content_type: application/zip

        - name: Publish release
          uses: eregon/publish-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            release_id: ${{ steps.create_release.outputs.id }}