on:
    push:
        tags:
            - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
    workflow_dispatch:   # Run manually

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        permissions:
            contents: write

        steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Zip Data Pack
          run: zip -r ${{ github.workspace }}/creeper-birthday-party-datapack-${{ github.ref_name }}.zip .
          working-directory: ${{ github.workspace }}/datapacks/creeper-birthday-party/

        - name: Zip Resource Pack
          run: zip -r ${{ github.workspace }}/creeper-birthday-party-resourcepack-${{ github.ref_name }}.zip .
          working-directory: ${{ github.workspace }}/resourcepacks/creeper-birthday-party/

        - name: Create github Release
          uses: softprops/action-gh-release@v1
          # if: startsWith(github.ref, 'refs/tags/')
          with:
            files: creeper-birthday-party-*.zip
            name: ${{ github.ref_name }}
            draft: true
            prerelease: false
            body: ${{ github.event.head_commit.message }}
